import type {
  BusinessProfile,
  CatalogItem,
  MarketplaceCategory,
} from "./types";

/**
 * Datos locales exclusivamente visuales para adelantar la Fase 1.
 * Todos los nombres, códigos de salón, precios y horarios son demostrativos.
 */
export const mockCategories: MarketplaceCategory[] = [
  {
    slug: "celulares-y-accesorios",
    name: "Celulares y accesorios",
    shortName: "Celulares",
    eyebrow: "Conectividad personal",
    description:
      "Compará comercios de celulares, cargadores, fundas y accesorios dentro de Shopping AYC, en el Mercado 4 de Asunción.",
    searchIntent:
      "Para quienes buscan resolver una compra móvil en un solo lugar y hablar directamente con el comercio antes de visitar.",
    buyerQuestions: [
      "¿El accesorio es compatible con mi marca y modelo?",
      "¿El precio y la disponibilidad fueron confirmados hoy?",
      "¿Qué garantía o cambio ofrece el comercio?",
    ],
  },
  {
    slug: "servicio-tecnico",
    name: "Servicio técnico",
    shortName: "Reparaciones",
    eyebrow: "Diagnóstico y reparación",
    description:
      "Encontrá técnicos para celulares, notebooks y equipos electrónicos en el corazón del Mercado 4.",
    searchIntent:
      "Para clientes que necesitan diagnóstico, plazo estimado y una conversación directa antes de dejar su equipo.",
    buyerQuestions: [
      "¿El diagnóstico tiene costo y cuánto demora?",
      "¿La reparación incluye garantía escrita?",
      "¿Cómo se protege la información del equipo?",
    ],
  },
  {
    slug: "informatica-y-seguridad",
    name: "Informática y seguridad",
    shortName: "Informática",
    eyebrow: "Equipamiento y conectividad",
    description:
      "Soluciones demostrativas de informática, redes, cámaras y conectividad para hogares y empresas.",
    searchIntent:
      "Para comparar equipamiento o pedir una cotización técnica según el espacio, la cantidad y el uso previsto.",
    buyerQuestions: [
      "¿Qué instalación y configuración están incluidas?",
      "¿El equipo tiene soporte y garantía local?",
      "¿La cotización contempla materiales y mano de obra?",
    ],
  },
];

export const mockBusinessProfiles: BusinessProfile[] = [
  {
    id: "demo-profile-conecta-movil",
    slug: "conecta-movil-demo",
    publicName: "Conecta Móvil Demo",
    categorySlug: "celulares-y-accesorios",
    summary: "Accesorios móviles y soluciones rápidas para mantenerte conectado.",
    description:
      "Esta ficha ilustra cómo un comercio podrá presentar su propuesta, especialidades, ubicación y catálogo autorizado sin exponer datos contractuales del inquilino.",
    specialties: ["Cargadores", "Fundas", "Protección"],
    unitCodes: ["PB-DEMO"],
    floorLabel: "Planta Baja",
    locationHint: "Ubicación demostrativa dentro de la galería",
    publicWhatsapp: null,
    hoursLabel: "Horario demostrativo · lunes a sábado",
    isPublished: true,
    isDemo: true,
    verifiedAt: null,
  },
  {
    id: "demo-profile-mundo-accesorio",
    slug: "mundo-accesorio-demo",
    publicName: "Mundo Accesorio Demo",
    categorySlug: "celulares-y-accesorios",
    summary: "Protección, audio y accesorios para diferentes marcas y modelos.",
    description:
      "Ejemplo visual de una segunda tienda dentro de la misma categoría para probar comparación, enlaces internos y descubrimiento por intención.",
    specialties: ["Audio", "Vidrios", "Soportes"],
    unitCodes: ["PA-DEMO"],
    floorLabel: "Planta Alta",
    locationHint: "Ubicación demostrativa dentro de la galería",
    publicWhatsapp: null,
    hoursLabel: "Horario demostrativo · lunes a sábado",
    isPublished: true,
    isDemo: true,
    verifiedAt: null,
  },
  {
    id: "demo-profile-tecnofix",
    slug: "tecnofix-demo",
    publicName: "TecnoFix Demo",
    categorySlug: "servicio-tecnico",
    summary: "Diagnóstico y reparación demostrativa de celulares y notebooks.",
    description:
      "La ficha muestra cómo explicar un servicio, sus condiciones y el siguiente paso comercial sin inventar un precio antes de revisar el equipo.",
    specialties: ["Celulares", "Notebooks", "Diagnóstico"],
    unitCodes: ["PA-DEMO"],
    floorLabel: "Planta Alta",
    locationHint: "Ubicación demostrativa dentro de la galería",
    publicWhatsapp: null,
    hoursLabel: "Horario demostrativo · lunes a sábado",
    isPublished: true,
    isDemo: true,
    verifiedAt: null,
  },
  {
    id: "demo-profile-bytelab",
    slug: "bytelab-demo",
    publicName: "ByteLab Demo",
    categorySlug: "informatica-y-seguridad",
    summary: "Equipos, redes y soporte para hogares, oficinas y comercios.",
    description:
      "Ejemplo de una ficha orientada a necesidades B2B, con productos y servicios que requieren confirmar alcance antes de cotizar.",
    specialties: ["Notebooks", "Redes", "Soporte"],
    unitCodes: ["PB-DEMO"],
    floorLabel: "Planta Baja",
    locationHint: "Ubicación demostrativa dentro de la galería",
    publicWhatsapp: null,
    hoursLabel: "Horario demostrativo · lunes a sábado",
    isPublished: true,
    isDemo: true,
    verifiedAt: null,
  },
  {
    id: "demo-profile-vision-segura",
    slug: "vision-segura-demo",
    publicName: "Visión Segura Demo",
    categorySlug: "informatica-y-seguridad",
    summary: "Cámaras, conectividad e instalación técnica según cada espacio.",
    description:
      "Esta ficha demuestra cómo captar una solicitud de cotización y derivarla al especialista correcto con contexto suficiente.",
    specialties: ["CCTV", "Instalación", "Conectividad"],
    unitCodes: ["PA-DEMO"],
    floorLabel: "Planta Alta",
    locationHint: "Ubicación demostrativa dentro de la galería",
    publicWhatsapp: null,
    hoursLabel: "Horario demostrativo · lunes a sábado",
    isPublished: true,
    isDemo: true,
    verifiedAt: null,
  },
];

export const mockCatalogItems: CatalogItem[] = [
  {
    id: "demo-item-cargadores",
    slug: "cargadores-rapidos-demo",
    businessProfileId: "demo-profile-conecta-movil",
    kind: "product",
    name: "Cargadores rápidos",
    summary: "Opciones demostrativas para distintos conectores y potencias.",
    categorySlug: "celulares-y-accesorios",
    priceType: "from",
    priceAmount: 75000,
    priceCurrency: "PYG",
    availability: "in_stock",
    attributes: ["Compatibilidad a confirmar", "Garantía demostrativa"],
    isPublished: true,
    isDemo: true,
    verifiedAt: null,
  },
  {
    id: "demo-item-proteccion",
    slug: "fundas-y-proteccion-demo",
    businessProfileId: "demo-profile-conecta-movil",
    kind: "product",
    name: "Fundas y protección",
    summary: "Fundas y vidrios según marca y modelo del equipo.",
    categorySlug: "celulares-y-accesorios",
    priceType: "from",
    priceAmount: 35000,
    priceCurrency: "PYG",
    availability: "limited",
    attributes: ["Varios modelos", "Colocación a confirmar"],
    isPublished: true,
    isDemo: true,
    verifiedAt: null,
  },
  {
    id: "demo-item-audio",
    slug: "audio-portatil-demo",
    businessProfileId: "demo-profile-mundo-accesorio",
    kind: "product",
    name: "Audio portátil",
    summary: "Auriculares y parlantes demostrativos para uso diario.",
    categorySlug: "celulares-y-accesorios",
    priceType: "quote",
    priceAmount: null,
    priceCurrency: "PYG",
    availability: "on_request",
    attributes: ["Modelos a confirmar", "Consulta directa"],
    isPublished: true,
    isDemo: true,
    verifiedAt: null,
  },
  {
    id: "demo-item-diagnostico",
    slug: "diagnostico-tecnico-demo",
    businessProfileId: "demo-profile-tecnofix",
    kind: "service",
    name: "Diagnóstico técnico",
    summary: "Revisión inicial del equipo y orientación sobre la reparación.",
    categorySlug: "servicio-tecnico",
    priceType: "quote",
    priceAmount: null,
    priceCurrency: "PYG",
    availability: "service_available",
    attributes: ["Plazo a confirmar", "Presupuesto previo"],
    isPublished: true,
    isDemo: true,
    verifiedAt: null,
  },
  {
    id: "demo-item-pantalla",
    slug: "cambio-de-pantalla-demo",
    businessProfileId: "demo-profile-tecnofix",
    kind: "service",
    name: "Cambio de pantalla",
    summary: "Servicio sujeto al modelo, repuesto disponible y diagnóstico.",
    categorySlug: "servicio-tecnico",
    priceType: "quote",
    priceAmount: null,
    priceCurrency: "PYG",
    availability: "on_request",
    attributes: ["Repuesto a confirmar", "Garantía según trabajo"],
    isPublished: true,
    isDemo: true,
    verifiedAt: null,
  },
  {
    id: "demo-item-notebook",
    slug: "notebook-trabajo-demo",
    businessProfileId: "demo-profile-bytelab",
    kind: "product",
    name: "Notebook para trabajo",
    summary: "Configuración recomendada según programas, presupuesto y movilidad.",
    categorySlug: "informatica-y-seguridad",
    priceType: "quote",
    priceAmount: null,
    priceCurrency: "PYG",
    availability: "on_request",
    attributes: ["Configuración a medida", "Stock a confirmar"],
    isPublished: true,
    isDemo: true,
    verifiedAt: null,
  },
  {
    id: "demo-item-redes",
    slug: "instalacion-de-red-demo",
    businessProfileId: "demo-profile-bytelab",
    kind: "service",
    name: "Instalación de red",
    summary: "Relevamiento, materiales y configuración para cada ambiente.",
    categorySlug: "informatica-y-seguridad",
    priceType: "quote",
    priceAmount: null,
    priceCurrency: "PYG",
    availability: "service_available",
    attributes: ["Visita técnica", "Cotización por alcance"],
    isPublished: true,
    isDemo: true,
    verifiedAt: null,
  },
  {
    id: "demo-item-cctv",
    slug: "kit-camaras-demo",
    businessProfileId: "demo-profile-vision-segura",
    kind: "service",
    name: "Proyecto de cámaras",
    summary: "Diseño demostrativo según puntos, cobertura y almacenamiento.",
    categorySlug: "informatica-y-seguridad",
    priceType: "quote",
    priceAmount: null,
    priceCurrency: "PYG",
    availability: "service_available",
    attributes: ["Relevamiento previo", "Instalación opcional"],
    isPublished: true,
    isDemo: true,
    verifiedAt: null,
  },
];
